refactor all modpack

diff --git a/.github/workflows/static.yml b/.github/workflows/static.yml
--- a/.github/workflows/static.yml
+++ b/.github/workflows/static.yml
@@ -3,7 +3,6 @@ name: Deploy packwiz pack to GitHub Pages
 on:
   push:
     branches: ["main"]
-    paths: ["modpack/**"]
 
   workflow_dispatch:
 
@@ -23,7 +22,6 @@ jobs:
       url: ${{ steps.deployment.outputs.page_url }}
     runs-on: ubuntu-latest
     steps:
-      # Error handler
       - name: Checkout main branch
         uses: actions/checkout@v7
         continue-on-error: true
@@ -31,41 +29,16 @@ jobs:
           ref: main
           path: main
 
-      # - name: Checkout dev branch
-      #   uses: actions/checkout@v7
-      #   continue-on-error: true
-      #   with:
-      #     ref: dev
-      #     path: dev
-
-      # workflow steps
-      - name: Prepare output folder
+      - name: Prepare output
         run: |
           mkdir -p out
           echo "<h1>Modpack Repository</h1><p>Status: 200 OK</p>" > out/index.html
-
-          build_pack() {
-            local branch=$1
-            local version=$2
-            
-            if [ -d "$branch/$version" ]; then
-              echo "Memproses branch $branch versi $version..."
-              
-              mkdir -p out/$branch/$version
-              cp -r $branch/$version/* out/$branch/$version/
-              
-              if [ -d "out/$branch/$version/mmcpack" ]; then
-                (cd $branch/$version/mmcpack && zip -q -r ../../../out/$branch/$version/Funautic.zip .)
-                echo "-> Funautic.zip berhasil dibuat dan folder mmcpack tetap dipertahankan."
-              else
-                echo "-> Peringatan: Folder mmcpack tidak ditemukan di $branch/$version. Zip diabaikan."
-              fi
-            else
-              echo "Info: Folder $version tidak ada di branch $branch. Dilewati."
-            fi
-          }
-
-          build_pack main modpack
+          if [ -d "main/mmcpack" ]; then
+            (cd main/mmcpack && zip -q -r ../../out/funautic.zip .)
+          else
+            echo "Canceled due error script"
+            exit 1
+          fi
 
       - name: Setup Pages
         uses: actions/configure-pages@v6
